import type { Metadata } from "next";
import { yekanBakh } from "./fonts/yekanBakh";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="rtl">
      <body className={yekanBakh.className}>{children}</body>
    </html>
  );
}
